bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/ObsDao.java, bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/impl/ObsDaoImpl.java, bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/BahmniObsService.java, bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/impl/BahmniObsServiceImpl.java, bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/BahmniObsServiceImplIT.java, bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/BahmniObsServiceImplTest.java, bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/display/controls/BahmniObservationsController.java, bahmnicore-omod/src/test/java/org/bahmni/module/bahmnicore/web/v1_0/controller/BahmniObservationsControllerTest.java
After OpenMRS 2.x upgrade the logic of Obs save changed. i.e when there is a change on obsTree at root level then entire tree will be replicated creating new Obs i.e the old obs uuid used to load the editobs page i.e 'patient.dashboard.observation' angular state is no more valid and the page throws exception.
To fix that we need to retrieve the revised obs when the obs is voided for replication.
This commit is to enhance the Bahmni Observation controller observation endpoint with ability to return revised obs when revision=latest is requested or else default.
=> Swathi | #3321 | Enhanced Bahmni Observation endpoint to retrieve revised obs with revision=latest parameter

admin/pom.xml, bahmni-emr-api/pom.xml, bahmni-mapping/pom.xml, bahmni-test-commons/pom.xml, bahmnicore-api/pom.xml, bahmnicore-omod/pom.xml, bahmnicore-omod/src/main/resources/config.xml, bahmnicore-ui/pom.xml, jss-old-data/pom.xml, obs-relation/pom.xml, openmrs-elis-atomfeed-client-omod/pom.xml, pom.xml, reference-data/api/pom.xml, reference-data/omod/pom.xml, reference-data/pom.xml, vagrant-deploy/pom.xml
- Update all sub project (module) versions to 0.93-SNAPSHOT as well. Only the main pom.xml was updated.
- Refactor the module version to clearly distinguish Bahmni Core deps from Bahmni Java Utils deps using Maven variables.
- Use Maven vars to avoid having to manually type the depending versions.
=> BAH-837 | Update modules version to 0.93-SNAPSHOT

bahmnicore-api/pom.xml, openmrs-elis-atomfeed-client-omod/pom.xml
BAH-851 | downgrading web-clients dependency for bahmni-core:release-0.92. provided httpclient library version is 4.2 by idgen
=> BAH-851 | downgrading web-clients dependency for bahmni-core:release-0.92

.travis.yml
No JIRA ticket for this "meta" issue.
=> Travis to use 'openjdk8' instead of 'oraclejdk8'

openmrs-elis-atomfeed-client-omod/src/main/java/org/bahmni/module/elisatomfeedclient/api/Constants.java, openmrs-elis-atomfeed-client-omod/src/main/java/org/bahmni/module/elisatomfeedclient/api/mapper/AccessionHelper.java, openmrs-elis-atomfeed-client-omod/src/test/java/org/bahmni/module/elisatomfeedclient/api/mapper/AccessionHelperTest.java
Added a global property `elisatomfeedclient.discontinueCancelledOrders` type boolean  to let user decide whether to discontinue bahmni orders if order is cancelled in openelis.
=> BAH-1077 | fix to disable modification of orders in Bahmni after editing the sample in ELIS during sample collection

bahmnicore-omod/src/main/resources/liquibase.xml
From Slack conversation: https://bahmni.slack.com/archives/C03LWT96L/p1607424210243800
Typo introduced in [this commit](https://github.com/Bahmni/bahmni-core/blob/51d0bd7410a34c9d1376068073d4a8fba770d0c1/bahmnicore-omod/src/main/resources/liquibase.xml#L4547)
```
defines_parent_form_id`
```
=> BAH-790 | Fix typo in Liquibase file

admin/src/main/java/org/bahmni/module/admin/csv/service/CSVPatientService.java, admin/src/main/java/org/bahmni/module/admin/csv/utils/CSVUtils.java, admin/src/main/java/org/bahmni/module/admin/observation/CSVObservationHelper.java, admin/src/test/java/org/bahmni/module/admin/csv/persister/RelationshipPersisterTest.java, admin/src/test/java/org/bahmni/module/admin/csv/service/CSVPatientServiceTest.java, admin/src/test/java/org/bahmni/module/admin/csv/service/CSVRelationshipServiceTest.java, admin/src/test/java/org/bahmni/module/admin/observation/DiagnosisMapperTest.java, admin/src/test/java/org/bahmni/module/admin/observation/handler/Form1CSVObsHandlerTest.java, admin/src/test/java/org/bahmni/module/admin/observation/handler/Form2CSVObsHandlerTest.java, bahmnicore-omod/src/main/resources/liquibase.xml
Description: 
Given that a user has date concepts in the CSV (for both registrations and forms), when the user has date format as YYYY/MM/DD (i.e. using slash as separator), then the data should be successfully be imported in the concept.
Note: At present migration only supports hyphen as a separator in the date format, i.e. YYYY-MM-DD.
Added support for global property bahmni.admin.csv.upload.dateFormat
User can set a valid date format in global property
CSV dates will be parsed using the set dateFormat.
=> Rakesh, Siva | BAH-1157 | Global Property CSV Date format support

pom.xml
This removes one of the obsolete repository `rubygems-releases` which causes the build to take long time.
=> BAH-1781 | Fix. Build taking longer time

bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/contract/patient/PatientSearchParameters.java
- Search By ID is throwing error when the user is having values for address attributes and addressSearchResultFields as empty {}
- Added a boundry condition to check addressSearchResultFields
=> BAH-2132 | Fix. Search by ID throws error without having address field in AddressSearchResultFields

bahmnicore-omod/src/test/java/org/bahmni/module/bahmnicore/web/v1_0/controller/display/controls/ObsToObsTabularFlowSheetControllerTest.java
Passed raw data when comparing with argument matchers in eq(data) and mocked the controller instead of directly using it.
=> BAH-1888 | Test mechanism failure tests are fixed in ObsToObsTabularFlowSheetControllerTest.java for build success

bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/impl/PatientDaoImpl.java
JIRA Card -> https://bahmni.atlassian.net/browse/BAH-1947
- Raised below PR to openmrs-core to enable Sort on the "identifier" field in the **PatientIdentfier.class**
[https://github.com/openmrs/openmrs-core/pull/4145](https://github.com/openmrs/openmrs-core/pull/4145)
- This PR **should** be merged only when the above PR merged to openmrs-core and new openmrs version is updated in the bahmni-core.
=> Bindu | BAH-1947 | Enable Sort option for registration lucene patientidentifier search

.github/workflows/build_publish.yml, .github/workflows/validate_pr.yml
In this PR, caching the maven dependencies which improves the build time based on hash of pom files. If the content of pom.xml changes, GHA build creates hash again.
1st Run: 
2nd Run: 
3rd Run:
=> Siva Reddy | Caching maven dependencies

bahmni-emr-api/pom.xml, bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/encountertransaction/command/impl/BahmniDiagnosisAnswerConceptSaveCommandImpl.java, bahmni-emr-api/src/test/java/org/openmrs/module/bahmniemrapi/encountertransaction/command/impl/BahmniDiagnosisAnswerConceptSaveCommandImplTest.java, bahmnicore-omod/pom.xml, bahmnicore-omod/src/main/resources/config.xml, pom.xml
JIRA - https://bahmni.atlassian.net/browse/BS-7
- Fetch concept details from Terminology Server
- Using the same fully specified same coming from Terminology Server while creating concept 
- Using preferred term as Short Name while creating concept 
- Mapping Terminology Server Code for the concept (Eg Map the code 61462000 , concept source SNOMED to Malaria concept)
- Adding newly created concept to Unclassified Concept Set
=> Siva Reddy | BS-7 | Diagnosis Save

bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/impl/ObsDaoImpl.java, bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/util/MiscUtils.java, bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/search/BahmniConceptSearchHandler.java, bahmnicore-omod/src/test/java/org/bahmni/module/bahmnicore/web/v1_0/search/BahmniConceptSearchHandlerTest.java
JIRA : https://bahmni.atlassian.net/browse/BAH-3266
Summary
------------
- Updating the custom search handler `openmrs/ws/rest/v1/concept?s=byFullySpecifiedName` to include system default locale also. 
- Also, updating the end point `openmrs/ws/rest/v1/bahmnicore/observations?concept=Height&concept=Weight&concept=BMI+Data&concept=BMI+Status+Data&patientUuid=781a7ce4-6d8e-44f0-91fe-de2278f5f100&scope=latest` which pulls latest obs data
=> BAH-3266 | Siva Reddy | Fetching concepts from default locale if no concepts in requested locale

bahmnicore-omod/src/main/resources/liquibase.xml
[JIRA link](https://bahmni.atlassian.net/browse/BAH-3336)
The dropdowns shown in programs module were not showing the linked conceptSet of Patient Stage post the OpenMRS upgrade. Changes at a database had to be made to support ConceptDataType in OpenMRS.
=> BAH-3336 | Patient Stage dropdown is empty in programs module [Env - Docker.standard]

openmrs-elis-atomfeed-client-omod/src/main/java/org/bahmni/module/elisatomfeedclient/api/worker/OpenElisAccessionEventWorker.java, openmrs-elis-atomfeed-client-omod/src/test/java/org/bahmni/module/elisatomfeedclient/api/worker/OpenElisAccessionEventWorkerTest.java
Card link - https://bahmni.atlassian.net/browse/BAH-3416?atlOrigin=eyJpIjoiMDdkY2ViNTg1ZTY1NDlhOWIwOTk2ZDEwYWEwZDI1ZjAiLCJwIjoiaiJ9
=> Add. Accession number for lab test performed in OpenElis to orders table

bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/forms2/service/impl/BahmniFormDetailsServiceImpl.java, bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/forms2/service/impl/BahmniFormDetailsServiceImplTest.java
- When a new patient uuid without visit is passed with this API `/openmrs/ws/rest/v1/bahmnicore/patient/4<uuid>/forms?formType=v2&numberOfVisits=10`, encounterSearch happens without any criteria.
- This returns all non-voided encounters from the database, due to which `OutOfMemory` happens.
- This fix adds a check the return empty list to the `getFormDetails` call, when no visit is returned for the patient.
Refactored test accordingly to validation getEncounter is not called when visits is empty.
JIRA: https://bahmni.atlassian.net/browse/BAH-3513
=> BAH-3513 | Fix. Disable encounter search when patient does not have visit

bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/forms2/service/impl/BahmniFormDetailsServiceImpl.java, bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/forms2/service/impl/BahmniFormDetailsServiceImplTest.java
related PR raised to product master - https://github.com/Bahmni/bahmni-core/pull/251
=> Bahmni-IPD-master-cherry-pick | BAH-3513 | Fix. Disable encounter search when patient does not have visit

bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/laborder/contract/LabOrderResults.java, bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/laborder/contract/TabularLabOrderResults.java
JIRA -> [BAH-3606](https://bahmni.atlassian.net/browse/BAH-3606)
In this PR, the panelName property is added to the orders in tabularResult in order to pass the panel details in the response for the labOrderResults url.
=> BAH-3606 | Add. panelName property in Orders in tabularResult

bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/VisitDocumentController.java, bahmnicore-omod/src/test/java/org/bahmni/module/bahmnicore/web/v1_0/controller/VisitDocumentControllerTest.java, pom.xml
JIRA -> [BAH-2833](https://bahmni.atlassian.net/browse/BAH-2833)
In this PR, a limit has been set to the document size so that if we try to upload a document having size greater than the limit, it will throw a 413, Payload Too Large status and prevents the uploading of the document.
=> Parvathy | BAH-2833 | Add. Size Limit To The Patient Documents

reference-data/api/src/main/java/org/bahmni/module/referencedata/labconcepts/contract/LabTest.java, reference-data/api/src/main/java/org/bahmni/module/referencedata/labconcepts/mapper/ConceptExtension.java, reference-data/api/src/main/java/org/bahmni/module/referencedata/labconcepts/mapper/DepartmentMapper.java, reference-data/api/src/main/java/org/bahmni/module/referencedata/labconcepts/mapper/PanelMapper.java, reference-data/api/src/main/java/org/bahmni/module/referencedata/labconcepts/mapper/SampleMapper.java, reference-data/api/src/main/java/org/bahmni/module/referencedata/labconcepts/mapper/TestAndPanelMapper.java, reference-data/omod/src/main/java/org/bahmni/module/referencedata/labconcepts/model/event/LabTestEvent.java, reference-data/omod/src/main/java/org/bahmni/module/referencedata/labconcepts/model/event/SaleableTypeEvent.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/labconcepts/model/event/AllTestsPanelsConceptSetEventTest.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/labconcepts/model/event/LabTestEventTest.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/web/contract/mapper/AllSamplesMapperTest.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/web/contract/mapper/AllTestsAndPanelsMapperTest.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/web/contract/mapper/LabTestMapperTest.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/web/contract/mapper/PanelMapperTest.java
This enhances the reference data OMOD to create events with title `test` when concept class is `Test`. 
JIRA: https://bahmni.atlassian.net/browse/BAH-3892
=> BAH-3892 | Support atomfeed test events for concepts with class Test

reference-data/api/src/main/java/org/bahmni/module/referencedata/labconcepts/contract/Sample.java, reference-data/api/src/main/java/org/bahmni/module/referencedata/labconcepts/mapper/AllSamplesMapper.java, reference-data/omod/src/main/java/org/bahmni/module/referencedata/labconcepts/model/event/SaleableTypeEvent.java, reference-data/omod/src/main/java/org/bahmni/module/referencedata/labconcepts/model/event/SampleEvent.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/labconcepts/advice/ConceptServiceEventInterceptorTest.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/labconcepts/model/event/SampleEventTest.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/web/contract/mapper/AllSamplesMapperTest.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/web/contract/mapper/LabTestMapperTest.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/web/contract/mapper/PanelMapperTest.java, reference-data/omod/src/test/java/org/bahmni/module/referencedata/web/contract/mapper/SampleMapperTest.java
This PR extends the `reference-data` OMOD to raise Atomfeed events of title Sample when a concept with class `Specimen` is saved. This is added to support sync of CIEL metadata mappings
=> BAH-4026 | Raise Sample event when the concept class is Specimen

bahmnicore-omod/src/main/resources/config.xml, bahmnicore-omod/src/main/resources/liquibase.xml
This PR adds the missing privilege `Get Patient Program Attribute Types` which is used by Programs display control
=> BAH-4045 | Add. Privilege for getting program attribute types

bahmnicore-omod/src/main/resources/config.xml
JIRA -> [BAH-3971](https://bahmni.atlassian.net/browse/BAH-3971)
This PR introduces the `contextCookieExpirationTimeInMinutes` global property via `config.xml`. This property defines the expiration time of the cookie that maintains the user's session context. It ensures that the user's session remains active for a specified duration, enhancing the user experience and security.
=> BAH-3971 | Add. contextCookieExpirationTimeInMinutes Global Property

bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/impl/BahmniConceptDaoImpl.java
This PR fixes the `getConceptsByFullySpecifiedName` method to return only the concepts which are not retired.
This fix is essential when using concepts from CIEL dictionary where there are concepts which are retired but their associated concept name are not voided.
Example: https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/140156/
https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/1342/
=> BAH-4065 | Fix. Get Concept by FSN should return only unretired concepts

bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/PatientDocumentServiceImplTest.java, bahmnicore-omod/src/test/java/org/bahmni/module/bahmnicore/web/v1_0/controller/BahmniPatientProfileResourceTest.java, pom.xml
This PR upgrades the dependency version to the latest modules used in distro for the upcoming bahmni-core release of 1.2.0
=> BAH-4090 | Refactor. Upgrade dependencies for release

pom.xml
- Updated Maven configuration to use Sonatype Central Portal for publishing artifacts
- Removed obsolete Sonatype OSS Nexus repository configurations
- Added central-publishing-maven-plugin to support the new publishing workflow
JIRA: https://bahmni.atlassian.net/browse/BAH-4172
=> BAH-4172 | Refactor. Migrate to Sonatype Central Portal Publishing
