- bahmnicore-omod/src/main/resources/liquibase.xml
Add migration for Non-Coded Condition and 'conditionList.nonCodedUuid' global_property.
> Sidtharthan, Gaurav | possible#Condition list Implementation

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/impl/ObsDaoImpl.java
- bahmnicore-api/src/test/resources/obsTestData.xml
Add concept names in 'sp' locale in obsTestData.xml dataset to add multi-locale scenario, with same Fully Specified Name.
Modify the ObsDaoImpl queries to handle this case and filter the result by locale.
> rbuisson | #3613 | Modify ObsDaoImpl queries to limit result by locale

- bahmnicore-omod/src/main/resources/liquibase.xml
https://bahmni.atlassian.net/browse/BAH-489
Add required OT viewing, editing privileges and roles and mapping among them
bahmnicore-omod/src/main/resources/liquibase.xml file only has been changed
> BAH-489 | Add OT required privileges as part of OT merging

- admin/src/test/java/org/bahmni/module/admin/csv/persister/ConceptPersisterIT.java
- admin/src/test/java/org/bahmni/module/admin/csv/persister/ConceptSetPersisterIT.java
- reference-data/api/src/main/java/org/bahmni/module/referencedata/labconcepts/mapper/ConceptCommonMapper.java
- reference-data/api/src/main/java/org/bahmni/module/referencedata/labconcepts/service/impl/ReferenceDataConceptServiceImpl.java
During CSV Upload if the UUIDs are specified in the CSV the new concepts will be created with the given UUID.
[Jira Card](https://bahmni.atlassian.net/browse/BAH-403)
> CSV Upload, Creating concepts with the given UUID.

- README.md
(Mainly doing this to test the CLA workflow.)
> Remove an extra blank line

- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/search/BahmniProviderSearchHandler.java
- bahmnicore-omod/src/test/java/org/bahmni/module/bahmnicore/web/v1_0/search/BahmniProviderSearchHandlerIT.java
- bahmnicore-omod/src/test/resources/providerDataSet.xml
For more context, see: https://bahmni.atlassian.net/browse/BAH-755
> BAH-755 | SearchHandler for Attribute based search for Providers

- reference-data/omod/src/main/java/org/bahmni/module/referencedata/labconcepts/model/Operation.java
- reference-data/omod/src/main/java/org/bahmni/module/referencedata/labconcepts/model/event/ConceptServiceEventFactory.java
- reference-data/omod/src/main/java/org/bahmni/module/referencedata/labconcepts/model/event/SaleableTypeEvent.java
- reference-data/omod/src/main/resources/liquibase.xml
- reference-data/omod/src/test/java/org/bahmni/module/referencedata/labconcepts/model/event/SaleableTypeEventTest.java
- reference-data/omod/src/test/java/org/bahmni/module/referencedata/web/contract/mapper/AttributableResourceMapperTest.java
- reference-data/omod/src/test/java/org/bahmni/module/referencedata/web/controller/ConceptOperationControllersIT.java
- reference-data/omod/src/test/resources/labDataSetup.xml
- changed java class names and variables, constants etc
- changed liquibase changeset 
- changed test data setup
> BAH-406 | renaming classes and variables from sellable to saleable

- admin/src/main/java/org/bahmni/module/admin/csv/service/CSVPatientService.java
> BAH-677 and BAH-679: CSV upload empty Field failure

- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/encountertransaction/advice/BahmniEncounterTransactionUpdateAdvice.java
- bahmni-emr-api/src/test/java/org/openmrs/module/bahmniemrapi/encountertransaction/advice/BahmniEncounterTransactionUpdateAdviceTest.java
https://bahmni.atlassian.net/browse/BAH-951
> Missing "/" when trying to load Groovy scripts

- bahmnicore-omod/src/main/resources/V1_61__CreatingGlobalPropertyForPatientIdentifierType.sql
- bahmnicore-omod/src/main/resources/liquibase.xml
Ticket : https://bahmni.atlassian.net/browse/BAH-828
> Unable to apply Bahmni Liquibase changes on a 'fresh' OpenMRS database.

- bahmnicore-omod/src/main/resources/liquibase.xml
> Bindu | BAH-1056 | Bahmni-core liquibase migration failing while adding REFERRED_OUT concept

- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/encountertransaction/command/impl/BahmniVisitAttributeService.java
https://bahmni.atlassian.net/browse/BAH-1085
> Bindu,Tarun | BAH-1085 | Add condition to ignore saveVisit() for the existing visit which is of "CONSULTATION" encounter type

- admin/src/test/java/org/bahmni/module/admin/observation/ObservationMapperIT.java
- admin/src/test/resources/Vitals_1.json
- admin/src/test/resources/conceptSetup.xml
https://bahmni.atlassian.net/browse/BAH-1030
> Supriya, Vinisha | BAH-1030 | MOBN-1516 | Fix integration test failure

- jss-old-data/pom.xml
> Upgrade MySQL connector from 5.1.8 to 5.1.48

- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/disposition/contract/BahmniDisposition.java
- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/disposition/mapper/BahmniDispositionMapper.java
- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/disposition/service/BahmniDispositionService.java
- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/disposition/service/BahmniDispositionServiceImpl.java
- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/drugorder/contract/BahmniDrugOrder.java
- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/drugorder/mapper/BahmniDrugOrderMapper.java
- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/laborder/contract/LabOrderResult.java
- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/laborder/service/LabOrderResultsServiceImpl.java
- bahmni-emr-api/src/test/java/org/openmrs/module/bahmniemrapi/disposition/mapper/BahmniDispositionMapperTest.java
- bahmni-emr-api/src/test/java/org/openmrs/module/bahmniemrapi/disposition/service/BahmniDispositionServiceTest.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/impl/BahmniDrugOrderServiceImpl.java
- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/BahmniDispositionController.java
- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/BahmniDrugOrderController.java
- bahmnicore-omod/src/test/java/org/bahmni/module/bahmnicore/web/v1_0/mapper/BahmniDrugOrderMapperTest.java
BAH-1045
BAH-1064
BAH-1046
BAH-1065
> BAH-987|Buvaneswari|Internationalisation changes for disposition,labresults and drug order

- bahmnicore-omod/src/main/resources/liquibase.xml
> BAH-1104|BAH-790|Buvaneswari|Regression-FormPrivilege table modification in liquibase

- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/laborder/service/LabOrderResultsServiceImpl.java
- bahmni-emr-api/src/test/java/org/openmrs/module/bahmniemrapi/laborder/service/LabOrderResultsServiceIT.java
- bahmni-emr-api/src/test/resources/labOrderAssociatedWithTestOrderData.xml
Ticket: https://bahmni.atlassian.net/browse/BAH-1134
> LabOrderResultsService.getAll() to support TestOrders.

- admin/src/main/java/org/bahmni/module/admin/csv/persister/EncounterPersister.java
- admin/src/main/java/org/bahmni/module/admin/csv/service/FormFieldPathGeneratorService.java
- admin/src/main/java/org/bahmni/module/admin/encounter/BahmniEncounterTransactionImportService.java
- admin/src/main/java/org/bahmni/module/admin/observation/CSVObservationHelper.java
- admin/src/main/java/org/bahmni/module/admin/observation/ObservationMapper.java
- admin/src/main/java/org/bahmni/module/admin/observation/handler/CSVObsHandler.java
- admin/src/main/java/org/bahmni/module/admin/observation/handler/Form1CSVObsHandler.java
- admin/src/main/java/org/bahmni/module/admin/observation/handler/Form2CSVObsHandler.java
- admin/src/test/java/org/bahmni/module/admin/csv/persister/EncounterPersisterIT.java
- admin/src/test/java/org/bahmni/module/admin/csv/service/FormFieldPathGeneratorServiceTest.java
- admin/src/test/java/org/bahmni/module/admin/encounter/BahmniEncounterTransactionImportServiceTest.java
- admin/src/test/java/org/bahmni/module/admin/observation/CSVObservationHelperTest.java
- admin/src/test/java/org/bahmni/module/admin/observation/ObservationMapperIT.java
- admin/src/test/java/org/bahmni/module/admin/observation/handler/Form2CSVObsHandlerTest.java
- admin/src/test/resources/Form2Encounters.json
- admin/src/test/resources/conceptSetup.xml
- admin/src/test/resources/form2DataSetup.xml
- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/AdminImportController.java
Approach :
- New End Point Created
- Reading form definition to get obs control properties (mandatory, allow future date, multi select and addmore)
- Validating mandatory and  allow future date properties.
- Creating multiple observations for multi select and add more obs.
- Using separate delimiters for multi select and add more obs which can be configured in global properties
> Siva | BAH-1146 | Changes for form2 encounter validations

- admin/pom.xml
- admin/src/main/java/org/bahmni/module/admin/csv/persister/PatientPersister.java
- admin/src/main/java/org/bahmni/module/admin/csv/service/CSVPatientService.java
- admin/src/main/resources/moduleApplicationContext.xml
- admin/src/test/java/org/bahmni/module/admin/csv/service/CSVPatientServiceTest.java
- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/AdminImportController.java
Support for mandatory fields Patient Registration page in CSV upload
> Siva | BAH-1156 | Support for mandatory fields Patient Registration page in CSV upload

- admin/src/main/java/org/bahmni/module/admin/csv/models/SectionPositionValue.java
- admin/src/main/java/org/bahmni/module/admin/csv/service/FormFieldPathGeneratorService.java
- admin/src/main/java/org/bahmni/module/admin/observation/CSVObservationHelper.java
- admin/src/main/java/org/bahmni/module/admin/observation/handler/Form2CSVObsHandler.java
- admin/src/test/java/org/bahmni/module/admin/csv/service/FormFieldPathGeneratorServiceTest.java
- admin/src/test/java/org/bahmni/module/admin/observation/handler/Form2CSVObsHandlerTest.java
- bahmnicore-omod/pom.xml
Approach used: 
- Using attribute to specify value in JSON format (isJson=true)
- Specify multiple values in JSON format [key: values]
- Specify array of values for add more section’s observation.  
for full details, check [BAH-1205](https://bahmni.atlassian.net/browse/BAH-1205)
> Siva | BAH-1205 | Support for Addmore section

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/contract/patient/PatientSearchParameters.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/impl/BahmniPatientServiceImpl.java
this will replace older search implementation completely. code is marked deprecated. should be removed in next ver
> BSL01 | removing version support. 

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/util/MiscUtils.java
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/util/MiscUtilsTest.java
- bahmnicore-omod/src/main/java/org/openmrs/module/bahmnicore/web/v1_0/resource/ProgramAttributeTypeResource.java
Ticket: https://bahmni.atlassian.net/browse/BAH-1237
> BAH-1237: ProgramAttributeTypeResource.getConcept to support concept UUID.

- bahmnicore-omod/src/main/resources/V1_99_AddLabLiteAppPrivilege.sql
- bahmnicore-omod/src/main/resources/liquibase.xml
co-authored by Priyanka Ajmera<pajmera@thoughtworks.com>
> BAH-1497 | Add. create new lab-lite privilege

- admin/src/test/java/org/bahmni/module/admin/observation/ObservationMapperIT.java
- bahmnicore-omod/src/main/resources/V1_99_AddLabLiteAppPrivilege.sql
- bahmnicore-omod/src/main/resources/config.xml
- bahmnicore-omod/src/main/resources/liquibase.xml
- pom.xml
https://bahmni.atlassian.net/browse/BAH-1497
> BAH-1497 | Refactor. move lablite privilege from liquibase.xml to config.xml

- .github/workflows/validate_pr.yml
- pom.xml
This PR is about 
- Upgrading Openmrs version to 2.1.7 to remove struts vulnerability
> BAH-1872 - | Rohit | - Upgrades openmrs version to 2.1.7

- bahmnicore-omod/src/main/resources/liquibase.xml
Please refer this [JIRA](https://bahmni.atlassian.net/browse/BAH-1868) card for more information
Co-authored-by: stavtnameh <hemanth.v@beehyv.com>
> BAH-1868 | Fix. Liquibase errors for column rename of `precise` in concept_numeric table.

- pom.xml
- Upgrading bacteriology version to 1.3.0
> BAH-1649 - | Rohit | - Upgrades bacteriology version to 1.3.0

- admin/src/main/java/org/bahmni/module/admin/csv/persister/PatientPersister.java
- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/AdminImportController.java
JIRA Link -> [https://bahmni.atlassian.net/browse/BAH-1955](https://bahmni.atlassian.net/browse/BAH-1955)
> Bindu | BAH-1955 | Fix bean creation exception with RegistrationPageService

- bahmnicore-omod/src/main/resources/BahmniBMPatientListInWard.sql
- Resolves BedManagement_Patient_List_In_Ward property insertion in global_property SQL issue
> BAH-1935 - | Rohit | - Resolves sql syntax error

- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/order/contract/BahmniOrder.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/impl/BahmniOrderServiceImpl.java
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/BahmniOrderServiceImplTest.java
Jira -> [https://bahmni.atlassian.net/browse/BAH-2001](https://bahmni.atlassian.net/browse/BAH-2001)
> BAH-2001 | Arjun, Siva Reddy | Adding Provider UUID in Bahmni Order response

- admin/src/main/java/org/bahmni/module/admin/csv/persister/PatientPersister.java
- admin/src/main/resources/moduleApplicationContext.xml
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/impl/PatientDaoImpl.java
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/dao/impl/BahmniPatientDaoImplLuceneIT.java
- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/AdminImportController.java
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-1787](https://bahmni.atlassian.net/browse/BAH-1787)
As part of this PR
- Fixed the bean creation error with PatientRegistrationService
- Commented Lucene Sort functionality. This will be handled as part of [https://bahmni.atlassian.net/browse/BAH-1888](https://bahmni.atlassian.net/browse/BAH-1888)
> Bindu | BAH-1787 | Fix bean creation error with PatientRegistrationService

- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/BahmniOrderServiceImplTest.java
Jira -> [Jira -> https://bahmni.atlassian.net/browse/BAH-2001] (https://bahmni.atlassian.net/browse/BAH-2001)
> BAH-2001 | Arjun, Siva Reddy | Adding test to verify Bahmni Order details

- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/order/contract/BahmniOrder.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/impl/BahmniOrderServiceImpl.java
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/BahmniOrderServiceImplTest.java
JIRA link - https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/35?modal=detail&selectedIssue=BAH-2015
> BAH-2015 | Adding FulFillerStatus in Bahmni Order Response

- bahmnicore-omod/src/main/resources/liquibase.xml
- Fixing liquibase migration issue in bahmni-core with clean-db, 
- Added the card below
https://bahmni.atlassian.net/browse/BAH-2033
> BAH-2033 - | Rohit | - Fixes liquibase migration issue in bahmni-core with clean-db

- bahmnicore-omod/src/main/resources/addAtomfeedMigrations.xml
- bahmnicore-omod/src/main/resources/liquibase.xml
- Adding atomfeed migrations(below) to bahmni-core
https://github.com/ICT4H/atomfeed/blob/master/atomfeed-client/src/main/resources/sql/db_migrations.xml
- Please refer below card
https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/41?modal=detail&selectedIssue=BAH-2086
> BAH-2086 - | Rohit | - Adds atomfeed migrations to bahmni-core

- bahmnicore-omod/src/main/resources/liquibase.xml
Co-authored-by: deepthi-m <deepthi.mantena@thoughtworks.com>
Co-authored-by: Soorya Kumaran C <sooryakumaran.c@thoughtworks.com>
Co-authored-by: Himabindu T <tbindu@thoughtworks.com>
> BAH-2061 | updated versions for bahmni diagnosis concepts

- bahmnicore-omod/src/main/resources/liquibase.xml
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2061](https://bahmni.atlassian.net/browse/BAH-2061)
As part of the PR we are,
- Adding the version tag to existing diagnosis concepts
- Retiring the CEIL diagnosis concepts
> Bindu | BAH-2061 | Retire diagnosis CEIL concepts and add version to bahmni diagnosis concepts

- bahmnicore-omod/src/main/resources/liquibase.xml
Jeera card : https://bahmni.atlassian.net/browse/BAH-1814?atlOrigin=eyJpIjoiODFmZGY3ZTdkMGUxNDBjY2JkMzcyMDU4MzY1MmYxZDYiLCJwIjoiaiJ9
> BAH-1814 | Add primary identifier type uuid in metadata_term_mapping

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/model/Document.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/PatientDocumentService.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/impl/PatientDocumentServiceImpl.java
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/PatientDocumentServiceImplIT.java
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/PatientDocumentServiceImplTest.java
- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/VisitDocumentController.java
- bahmnicore-omod/src/test/java/org/bahmni/module/bahmnicore/web/v1_0/controller/VisitDocumentControllerTest.java
patient-documents-file-name-should-not-have-random-characters
> BAH-2100 | patient-documents-file-name-should-not-have-random-characters

- bahmnicore-omod/src/main/resources/liquibase.xml
- Correcting concept name to Coded Diagnosis in liquibase file
> BAH-2253 - [ Rohit, Soorya ] - Corrects concept name to Coded Diagnosis in liquibase file

- bahmnicore-omod/src/main/resources/liquibase.xml
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2265](https://bahmni.atlassian.net/browse/BAH-2265)
> Bindu | BAH-2265 | enable global property to use Legacy diagnosis service from emrapi

- pom.xml
OpenMRS Version Upgrade to 2.5.7-SNAPSHOT
> BAH-2274 | Siva Reddy | OpenMRS upgrade to 2.5.7-SNAPSHOT

- pom.xml
- Upgrading openmrs version to 2.5.7
> BAH-2278 - [ Rohit ] - Upgrades openmrs version to 2.5.7

- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/encountertransaction/mapper/ETObsToBahmniObsMapper.java
- bahmni-emr-api/src/test/java/org/openmrs/module/bahmniemrapi/encountertransaction/mapper/ETObsToBahmniObsMapperTest.java
- Resolving issue to display Form2 forms on patient dashboard
- Added check to validate whether is Form1 or Form2 
- Please refer jira issue: https://bahmni.atlassian.net/browse/BAH-2268
> BAH-2268 - [ Rohit ] - Resolves issue to display Form2 forms on patient dashboard

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/impl/PatientDaoImpl.java
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/dao/impl/BahmniPatientDaoImplLuceneIT.java
Fixed exception caused by non-patient user in pNames
> BAH-2354 | lucene search filtering both identifier and patient name,

- bahmni-emr-api/src/test/java/org/openmrs/module/bahmniemrapi/encountertransaction/advice/BahmniEncounterTransactionUpdateAdviceTest.java
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2450](https://bahmni.atlassian.net/browse/BAH-2450)
> Bindu | BAH-2450 | Temporarily Ignore test class to fix the build issue.

- .github/workflows/build_publish.yml
- .github/workflows/validate_pr.yml
- admin/pom.xml
- bahmni-emr-api/src/test/java/org/openmrs/module/bahmniemrapi/encountertransaction/advice/BahmniEncounterTransactionUpdateAdviceTest.java
- bahmnicore-omod/pom.xml
- bahmnicore-ui/pom.xml
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2450](https://bahmni.atlassian.net/browse/BAH-2450)
As part of this PR
1. Fixing the warning message that we see with the mvn build command
2. Changing Ubuntu image from latest to 22.04 to fix the failing test case
> Bindu | BAH-2450 | Fix the GHA for build and deploy workflow failing on bahmni-core master

- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/MvcConfiguration.java
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2062](https://bahmni.atlassian.net/browse/BAH-2062)
This PR
- Fix the issue of HTML API error response
> Bindu | BAH-2062 | Fix HTML error response issue with API's

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/contract/patient/search/PersonAttributeQueryHelper.java
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2456](https://bahmni.atlassian.net/browse/BAH-2456)
> Bindu | BAH-2456 | fix the issue with patient search by name and phone number API taking more time than usual

- bahmnicore-omod/src/main/java/org/openmrs/module/bahmnicore/web/v1_0/resource/BahmniObsResource.java
- Upgrading supportedOpenmrsVersions to support openmrs 2.*
- Jira: https://bahmni.atlassian.net/browse/BAH-2521
> BAH-2521 - [ Bindu, Rohit ] - Upgrades supportedOpenmrsVersions to support openmrs 2.*

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/SqlSearchService.java
- bahmnicore-api/src/main/resources/moduleApplicationContext.xml
This PR is about - 
- Adding AuthorizationAdvice bean to moduleApplicationContext to enable auth security to return 401 unauthorised message on api call without login
- Jira https://bahmni.atlassian.net/browse/BAH-2486
> BAH-2486 - [ Rohit ] - Adds AuthorizationAdvice bean to moduleApplicationContext to enable auth security

- bahmnicore-ui/src/main/java/org/bahmni/module/bahmnicoreui/constant/DiseaseSummaryConstants.java
- bahmnicore-ui/src/main/java/org/bahmni/module/bahmnicoreui/helper/ObsDiseaseSummaryAggregator.java
- bahmnicore-ui/src/main/java/org/bahmni/module/bahmnicoreui/mapper/DiseaseSummaryObsMapper.java
1. Added new flag for groupBy obsTime and modified the grouping logic to support the vitals flowsheet 
2. Added configuration to highlight the abnormal values in red in the flowsheet
Co-authored-by: deepthi-m <deepthi.mantena@thoughtworks.com>
> BAH-2415 | Added new flag for groupBy obsTime and modified the grouping logic to support the vitals flowsheet 

- bahmnicore-omod/src/main/resources/liquibase.xml
This PR is about
- Making modifications in liquibase changeset to resolve global_property duplications
> BAH-2678 - Makes modifications in liquibase changeset to resolve global_property duplications

- bahmnicore-omod/src/main/resources/liquibase.xml
- Adding migration to change bahmni.primaryIdentifierType global_property value
> BAH-2678 - Adds migration to change bahmni.primaryIdentifierType global_property value

- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/encountertransaction/mapper/ETObsToBahmniObsMapper.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/obs/handler/ImageUrlHandler.java
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2706](https://bahmni.atlassian.net/browse/BAH-2706)
> Bindu | BAH-2706 | Fix FileNotFound exception with complex_obs

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/obs/handler/VideoUrlHandler.java
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2706](https://bahmni.atlassian.net/browse/BAH-2706)
> Bindu | BAH-2706 | Fix Patient Video FileNotFound exception with complex_obs

- pom.xml
- Upgrading openmrs version to 2.5.10
> BAH-2407 - [ Rohit ] - Upgrades openmrs version to 2.5.10

- bahmnicore-omod/src/main/resources/liquibase.xml
JIRA Card: https://bahmni.atlassian.net/browse/BAH-2946
> BAH-2946 | Fix. Incorrect Drug Routes mapping

- bahmnicore-omod/pom.xml
- pom.xml
- Removing unused dependencies
> Siva Reddy | Removed unused dependencies

- admin/pom.xml
- bahmni-emr-api/pom.xml
- bahmni-mapping/pom.xml
- bahmni-test-commons/pom.xml
- bahmnicore-api/pom.xml
- bahmnicore-omod/pom.xml
- bahmnicore-ui/pom.xml
- obs-relation/pom.xml
- openmrs-elis-atomfeed-client-omod/pom.xml
- pom.xml
- reference-data/api/pom.xml
- reference-data/omod/pom.xml
- reference-data/pom.xml
- vagrant-deploy/pom.xml
- Incrementing version to 1.2.0-SNAPSHOT in all sub modules
> Incrementing development version to 1.2.0-SNAPSHOT

- pom.xml
JIRA - https://bahmni.atlassian.net/browse/BAH-3001
- Removing Packaging of lombok dependency in the module's lib directory
> BAH-3001 | Siva Reddy | Removing Packaging of lombok dependency

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/impl/BahmniDrugOrderServiceImpl.java
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/BahmniDrugOrderServiceImplTest.java
JIRA - https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/55?modal=detail&selectedIssue=BAH-3079
This PR has changes to get inpatient drug orders in both active and inactive drug order lists.
> BAH-3079 | Add InPatient drugs to Active and Inactive drug orders list

- bahmni-emr-api/src/main/java/org/openmrs/module/bahmniemrapi/order/contract/BahmniOrder.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/impl/BahmniOrderServiceImpl.java
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/BahmniOrderServiceImplTest.java
This PR adds the urgency field to the response of orders API
> Phani | A-1205069439065526 | Add Order urgency to fetch order API

- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/BahmniEncounterController.java
- bahmnicore-omod/src/test/java/org/bahmni/module/bahmnicore/web/v1_0/controller/BahmniEncounterControllerTest.java
"Co-authored-by: yenugukeerthana <keerthana.yenugu@thoughtworks.com>"
> BAH-3180 | Add. Bad Request Exception Handler for OrderEntryException

- bahmnicore-omod/src/main/java/org/openmrs/module/bahmnicore/web/v1_0/resource/BahmniObsResource.java
- adds providers info as part of the obs resource to be sent as part of the api call
Story ref : [BAH-3209](https://bahmni.atlassian.net/browse/BAH-3209)
> BAH-3209 | added provider info in the obs response

- .gitignore
- pom.xml
JIRA -> [BAH-3228](https://bahmni.atlassian.net/browse/BAH-3228)
In this PR, upgrades Bahmni Commons from its current release version, 1.0.0, to the snapshot version, 1.1.0-SNAPSHOT.
> BAH-3228 | Add. Bump Bahmni Commons Version

- bahmnicore-omod/src/main/resources/liquibase.xml
JIRA Card link. -> [https://bahmni.atlassian.net/browse/BAH-3269](https://bahmni.atlassian.net/browse/BAH-3269)
Asana card -> [https://app.asana.com/0/1204322126657135/1205556595128685/f](https://app.asana.com/0/1204322126657135/1205556595128685/f)
> Bindu | BAH-3269 | Fix the privileges issue with Program Attribute Types API call

- pom.xml
- fixed locale issue while saving Medication
> BAH-3361 | Updated. emrapi version

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/impl/ApplicationDataDirectoryImpl.java
- openmrs-elis-atomfeed-client-omod/src/main/java/org/bahmni/module/elisatomfeedclient/api/worker/OpenElisAccessionEventWorker.java
JIRA -> [BAH-3720](https://bahmni.atlassian.net/browse/BAH-3720)
> Parvathy | BAH-3720 | Fix. Append applicationDataDirectory File Path With File Separator

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/impl/ApplicationDataDirectoryImpl.java
JIRA -> [BAH-3720](https://bahmni.atlassian.net/browse/BAH-3720)
> Parvathy | BAH-3720 | Fix. Append applicationDataDirectory Path With File Separator

- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/VisitDocumentController.java
JIRA -> [BAH-2833](https://bahmni.atlassian.net/browse/BAH-2833)
This PR resolves the issue of an error being thrown due to an empty document size limit in bahmni-standard. As there is currently no limit set for document size in bahmni-standard, an exception was occurring. To mitigate this, I've implemented a condition to check for an empty value of the document size.
> Parvathy | BAH-2833 | Fix. Handle Error Due To Empty Document Size Limit In Bahmni Standard

- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/contract/NoteRequestResponse.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/NoteDao.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/dao/impl/NoteDaoImpl.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/mapper/NoteMapper.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/model/Note.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/model/NoteType.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/NoteService.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/service/impl/NoteServiceImpl.java
- bahmnicore-api/src/main/java/org/bahmni/module/bahmnicore/validator/NoteValidator.java
- bahmnicore-api/src/main/resources/NoteType.hbm.xml
- bahmnicore-api/src/main/resources/Notes.hbm.xml
- bahmnicore-api/src/main/resources/moduleApplicationContext.xml
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/service/impl/NoteServiceImplIT.java
- bahmnicore-api/src/test/java/org/bahmni/module/bahmnicore/validator/NoteValidatorTest.java
- bahmnicore-api/src/test/resources/notesData.xml
- bahmnicore-api/src/test/resources/test-hibernate.cfg.xml
- bahmnicore-omod/src/main/java/org/bahmni/module/bahmnicore/web/v1_0/controller/BahmniNotesController.java
- bahmnicore-omod/src/main/resources/config.xml
- bahmnicore-omod/src/main/resources/liquibase.xml
- create, update and delete APIs for OT notes
JIRA ref: [BAH-3117](https://bahmni.atlassian.net/browse/BAH-3117)
> BAH-3117 | Ability to add, edit and delete notes in OT module

- .github/workflows/build_publish.yml
- .github/workflows/release_deploy.yml
- pom.xml
This PR adds a workflow which can sign and deploy artifacts to staging on push of a tag.
> BAH-4090 | Add. Workflow to release artifacts on push of a tag

- bahmnicore-omod/src/main/resources/liquibase.xml
- bahmnicore-omod/src/main/resources/migrations/dependent-modules/liquibase.xml
This PR tries to ensure that changesets that run against MySQL database can also run against the MariaDB database.
> Liquibase changesets to run against MySQL and MariaDB databases.
